In [ ]:
#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

In [ ]:
#### 2. Print the numpy version and the configuration (★☆☆)

In [12]:
print(len(dir(np)))
print(np.__version__)
np.show_config()

618
1.19.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_info']
    libraries = ['openblas_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    library_dirs = ['D:\\a\\1\\s\\numpy\\build\\openblas_lapack_info']
    libraries = ['openblas_lapack_info']
    language = f77
    define_macros = [('HAVE_CBLAS', None)]


In [ ]:
#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
a = np.empty(10)
print(a)

[1.20990645e-312 0.00000000e+000 1.06395697e+224 2.16696845e+184
 2.22893995e+180 8.23037498e-071 1.03136502e+166 3.66432041e-086
 3.51151606e+151 1.16097027e-028]


In [ ]:
#### 4. How to find the memory size of any array (★☆☆)

In [24]:
a = np.arange(10).reshape(2,5)
b = a.dtype
c = a.itemsize
d = a.shape
e = a.size
f = c*e
print('array\n', a)
print('array data type:', b)
print('size of one item:', c)
print('shape:', d)
print('size:', e)
print('total mem size:', f)
print('number of bytes:', a.nbytes)

array
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array data type: int32
size of one item: 4
shape: (2, 5)
size: 10
total mem size: 40
number of bytes: 40


In [ ]:
#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [25]:
np.add?

Call signature:  np.add(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'add'>
File:            c:\users\tony\appdata\local\programs\python\python38-32\lib\site-packages\numpy\__init__.py
Docstring:      
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where 

In [ ]:
#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [27]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [28]:
a = np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [29]:
a = np.arange(10)
a = a[::-1]
print(a)

[9 8 7 6 5 4 3 2 1 0]


In [ ]:
#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [31]:
a = np.arange(9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [39]:
a = np.array([1,2,0,0,4,0])
b = np.where(a!=0)
print(b)
print(b[0])

(array([0, 1, 4], dtype=int32),)
[0 1 4]


In [37]:
a = np.arange(9).reshape(3,3)
b = np.where(a<5)
print(a)
print(b)
print(b[0])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(array([0, 0, 0, 1, 1], dtype=int32), array([0, 1, 2, 0, 1], dtype=int32))
[0 0 0 1 1]


In [38]:
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4], dtype=int32),)


In [ ]:
#### 11. Create a 3x3 identity matrix (★☆☆)

In [40]:
a = np.identity(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#### 12. Create a 3x3x3 array with random values (★☆☆)

In [43]:
a = np.random.randint(0, 10, (2, 3, 4))
print(a.size)
print(a)


24
[[[2 5 0 3]
  [9 3 7 3]
  [1 0 0 7]]

 [[6 0 7 3]
  [6 1 9 8]
  [9 1 5 8]]]


In [ ]:
#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [48]:
a = np.random.randint(0, 100, (5,10))
b = np.amin(a, 0)
c = np.amin(a, 1)
d = np.amax(a)
print(a)
print(b)
print(c)
print(d)

[[75  1 94  0 32  6 23 29 94  3]
 [50 21 36 45 13 52 27 40 40 89]
 [45 67 13 39 26 31 96 89 38 33]
 [38 17 17 70 90 50 33 66 27 51]
 [57 28 16 72 63 52 65 31  1  7]]
[38  1 13  0 13  6 23 29  1  3]
[ 0 13 13 17  1]
96


In [ ]:
#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [49]:
a = np.random.randint(0, 100, (30))
b = np.mean(a)
print(a)
print(b)


[ 4 77 95 92 56 34 70 23  9 81 72 95 21 83 73 11 46 80 95 72 77 26 65 75
 11 61 24 86 91 19]
57.46666666666667


In [ ]:
#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [52]:
a = np.zeros((5, 10))
a[:, 0] = 1
a[:, -1] = 1
a[0, :] = 1
a[-1, :] = 1
print(a)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [61]:
a = np.zeros((5, 10))
a[:, [0, -1]] = 1
a[[0, -1], :] = 1
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [53]:
Z = np.ones((5,10))
Z[1:-1, :] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [60]:
a = np.ones((5,10))
b = a.shape
c = tuple(i+2 for i in b)
d = np.zeros(c)
d[1:-1,1:-1] = a
e = np.pad(a, 2, mode='constant',constant_values=0 )
print(a, '\n', d, '\n', e)


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]] 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]] 
 [[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [ ]:
#### 17. What is the result of the following expression? (★☆☆)

In [ ]:
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [62]:
0 * np.nan

nan

In [63]:
np.nan == np.nan

False

In [64]:
np.inf > np.nan

False

In [65]:
np.nan - np.nan

nan

In [66]:
np.nan in set([np.nan])

True

In [67]:
0.3 == 3 * 0.1

False

In [70]:
a = list([np.nan])
b = np.nan in a
print(a, b)

[nan] True


In [76]:
a = [1, np.nan, 3]
for i in a:
    print(f'{i} == np.nan --> {i==np.nan}')
    print(f'{i} is np.nan --> {i is np.nan}')

1 == np.nan --> False
1 is np.nan --> False
nan == np.nan --> False
nan is np.nan --> True
3 == np.nan --> False
3 is np.nan --> False


In [ ]:
#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [82]:
a = np.zeros((5,5))
b = a[1:, :-1]
c = np.diag_indices(4)
b[c] = [1, 2, 3, 4]
print(a)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


In [84]:
a = np.diag([1, 2, 3, 4], k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [ ]:
#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [97]:
a = np.zeros((8,8))
a.flat[::2] = 1
a[1::2] = np.flip(a[1::2])
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [99]:
a = np.zeros((8,8))
a[::2, ::2] = 1
a[1::2, 1::2] = 1
print(a)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


In [ ]:
#### 20. Consider a (6,7,8) shape array, 
####     what is the index (x,y,z) of the 100th element?

In [ ]:
# (1,0,0) = 7*8 = 56
# represent 44
# 44/8 = 5.5
# (1,5,0) = 56 + 5*8 = 96
# (1,5,3) = 56 + 5*8 + 4 = 99


In [100]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)

In [ ]:
a = np.arange(50).reshape(5,10)
print(a)
a[::2] = 0
print(a)

In [ ]:
#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [104]:
a = np.tile([0, 1], 4)
b = np.tile([1, 0], 4)
c = np.concatenate((a,b))
c = np.tile(c, 4)
d = c.reshape(8,8)
print(d)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [109]:
a = np.array([[0,1],[1,0]])
b = np.tile( a, (2,4))
print(a)
print(b)

[[0 1]
 [1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
#### 22. Normalize a 5x5 random matrix (★☆☆)

In [111]:
a = np.random.randint(0, 100, (5,5))
b = np.linalg.det(a)
c = a/b
print(a, '\n', b, '\n', c)

[[36 11  3 24 35]
 [ 0 69 16 70 15]
 [35 14 40 47 98]
 [96 30 42 72  1]
 [24 83 85 94 28]] 
 -351513533.99999905 
 [[-1.02414264e-07 -3.12932474e-08 -8.53452203e-09 -6.82761762e-08
  -9.95694237e-08]
 [-0.00000000e+00 -1.96294007e-07 -4.55174508e-08 -1.99138847e-07
  -4.26726102e-08]
 [-9.95694237e-08 -3.98277695e-08 -1.13793627e-07 -1.33707512e-07
  -2.78794386e-07]
 [-2.73104705e-07 -8.53452203e-08 -1.19483308e-07 -2.04828529e-07
  -2.84484068e-09]
 [-6.82761762e-08 -2.36121776e-07 -2.41811458e-07 -2.67415024e-07
  -7.96555390e-08]]


In [ ]:
#### 23. Create a custom dtype that describes 
####       a color as four unsigned bytes (RGBA) (★☆☆)

In [117]:
a = np.dtype('B')
b = np.zeros((10,4), dtype=a)
print('{!r}'.format(b))

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=uint8)


In [119]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [128]:
a = np.random.rand(10, dtype=color)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [121]:
print(a)

[(1, 1, 1, 1) (1, 1, 1, 1) (1, 1, 1, 1) (1, 1, 1, 1) (1, 1, 1, 1)
 (1, 1, 1, 1) (1, 1, 1, 1) (1, 1, 1, 1) (1, 1, 1, 1) (1, 1, 1, 1)]


In [126]:
print(a[2]["a"])

1


In [ ]:
#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [132]:
a = np.random.rand(15).reshape((5,3))
b = np.random.rand(6).reshape((3,2))
c = a.dot(b)
print(c.shape, '\n', c)


(5, 2) 
 [[1.16142938 1.14509829]
 [0.84636764 1.01590477]
 [0.20460216 0.44739602]
 [0.68355791 0.67543363]
 [0.69049305 0.66821937]]


In [ ]:
#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [142]:
a = np.random.randint(0, 10, (30))
print(a)
b = np.where( (a>3) & (a<8))
a[b]= -a[b]
print(b)
print(a)

[6 5 2 0 8 8 5 9 5 4 7 8 3 6 2 4 1 3 9 6 4 3 9 7 6 9 9 5 1 1]
(array([ 0,  1,  6,  8,  9, 10, 13, 15, 19, 20, 23, 24, 27], dtype=int32),)
[-6 -5  2  0  8  8 -5  9 -5 -4 -7  8  3 -6  2 -4  1  3  9 -6 -4  3  9 -7
 -6  9  9 -5  1  1]


In [ ]:
Z = np.arange(11)
Z[(3 < Z) & (Z < 8)] *= -1
print(Z)

In [145]:
z = np.arange(11)
a = (z > 3)
b = (z < 8)
c = (a & b)
print(a)
print(b)
print(c)

[False False False False  True  True  True  True  True  True  True]
[ True  True  True  True  True  True  True  True False False False]
[False False False False  True  True  True  True False False False]


In [ ]:
#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [146]:
print(sum(range(5),-1))

9


In [147]:
print(np.sum(range(5),-1))

10


In [149]:
a = (np.range(5),-1)
print(a)

AttributeError: module 'numpy' has no attribute 'range'

In [ ]:
#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [152]:
Z=np.arange(10)

In [153]:
Z**Z

array([        1,         1,         4,        27,       256,      3125,
           46656,    823543,  16777216, 387420489], dtype=int32)

In [154]:
2 << Z >> 2

array([  0,   1,   2,   4,   8,  16,  32,  64, 128, 256], dtype=int32)

In [157]:
Z <- Z

array([False, False, False, False, False, False, False, False, False,
       False])

In [158]:
1j*Z

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j, 0.+5.j, 0.+6.j, 0.+7.j,
       0.+8.j, 0.+9.j])

In [159]:
Z/1/1

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [167]:
(Z>3) & (Z<8)

array([False, False, False, False,  True,  True,  True,  True, False,
       False])

In [170]:
-10//4

-3

In [ ]:
#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [171]:
np.array(0) / np.array(0)

<ipython-input-171-3585dcb7ab9b>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)


nan

In [173]:
# Division by zero always yields zero in integer arithmetic, 
# and does not raise an exception or a warning:
np.array(0) // np.array(0) 

<ipython-input-173-68ce7e467bdf>:1: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0) #Division by zero always yields zero in integer arithmetic, and does not raise an exception or a warning:


0

In [174]:
np.array(1.5) // np.array(0) 

<ipython-input-174-a6ccb72ff5a8>:1: RuntimeWarning: invalid value encountered in floor_divide
  np.array(1.5) // np.array(0)


nan

In [176]:
a = np.array([np.nan])
b = a.astype(int)  # Gives you max possible 32 bits int of 2147483648
c = a.astype(float)
d = b.astype(float)
print(a, b, c, d)

[nan] [-2147483648] [nan] [-2.14748365e+09]


In [ ]:
#### 29. How to round away from zero a float array ? (★☆☆)

In [178]:
a = np.arange(-3, 3, 0.5)
b = np.where(a<0, np.floor(a), np.ceil(a))
print(a, '\n', b)

[-3.  -2.5 -2.  -1.5 -1.  -0.5  0.   0.5  1.   1.5  2.   2.5] 
 [-3. -3. -2. -2. -1. -1.  0.  1.  1.  2.  2.  3.]


In [ ]:
#### 30. How to find common values between two arrays? (★☆☆)

In [180]:
a = np.arange(-5, 5)
b = np.arange(-3, 3)
c = np.union1d(a,b)
d = np.intersect1d(a,b)
print(a, '\n', b, '\n', c, '\n', b)


[-5 -4 -3 -2 -1  0  1  2  3  4] 
 [-3 -2 -1  0  1  2] 
 [-5 -4 -3 -2 -1  0  1  2  3  4] 
 [-3 -2 -1  0  1  2]


In [ ]:
#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [2]:
a = np.array(1.0) / 0
b = np.seterr(all='ignore')
c = np.array(1.0) / 0
d = np.seterr(**b)
print(a)
print(b)
print(c)
print(d)


inf
{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}
inf
{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}


<ipython-input-2-3b7cf0ba2dad>:1: RuntimeWarning: divide by zero encountered in true_divide
  a = np.array(1.0) / 0


In [ ]:
#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [3]:
a = np.sqrt(-1)
print(a)
b = np.emath.sqrt(-1)
print(b)

nan
1j


In [ ]:
#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [11]:
a = np.timedelta64(1, 'D')
b = np.datetime64('now')
c = b - a
d = b + a
print(a)
print(np.datetime_as_string(c, unit='D'))
print(np.datetime_as_string(b, unit='D'))
print(np.datetime_as_string(d, unit='D'))

1 days
2020-09-30
2020-10-01
2020-10-02


In [ ]:
#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [18]:
a = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


In [ ]:
#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [19]:
A = np.arange(10)
B = np.arange(10)
C = ((A + B) * (-A/2))

print(C)

[  0.  -1.  -4.  -9. -16. -25. -36. -49. -64. -81.]


In [ ]:
#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [21]:
a = np.random.random(12) * 10
b = np.floor(a)
print(a, b)

[6.10162998 7.33670946 3.19434907 3.92810676 2.05723242 7.63644957
 4.03261665 8.24836579 8.77062781 5.01429172 6.3830156  3.00234177] [6. 7. 3. 3. 2. 7. 4. 8. 8. 5. 6. 3.]


In [ ]:
#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [22]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [23]:
a = np.arange(5)
b = np.tile(a, (5,1))
print(b)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [ ]:
#### 38. Consider a generator function that generates 10 integers 
####      and use it to build an array (★☆☆)

In [25]:
a = (i**2 for i in range(10))
b = np.array(list(a))
print(a, '\n', b)

<generator object <genexpr> at 0x0EBDA370> 
 [ 0  1  4  9 16 25 36 49 64 81]


In [ ]:
#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [27]:
a = np.linspace(0, 1, 12)
b = a[1:-1]
print(a, b)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ] [0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
#### 40. Create a random vector of size 10 and sort it (★★☆)

In [28]:
a = np.random.random(10)
b = np.sort(a)
print (b)

[0.19230992 0.31080783 0.48657132 0.56004927 0.57166168 0.74906266
 0.75248942 0.79242481 0.869839   0.90226388]


In [ ]:
#### 41. How to sum a small array faster than np.sum? (★★☆)

In [ ]:
#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [ ]:
np.array_equal(a, b)

In [ ]:
#### 43. Make an array immutable (read-only) (★★☆)

In [ ]:
#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [34]:
def cart2pol(x, y):
    rho = np.sqrt(x**2 + y**2)
    phi = np.arctan2(y, x)
    return(rho, phi)

def pol2cart(rho, phi):
    x = rho * np.cos(phi)
    y = rho * np.sin(phi)
    return(x, y)
a = np.random.random((10,2))
rho, phi = cart2pol(a[:,0], a[:,1])

In [ ]:
#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [36]:
a = np.random.randint(0, 100, (10))
b = np.max(a)
c = np.where(a==b)
print(a)
print(b)
print(c)
a[c] = 0
print(a)

[ 8 89 50  9 20 38 33 26 77 59]
89
(array([1], dtype=int32),)
[ 8  0 50  9 20 38 33 26 77 59]


In [ ]:
#### 46. Create a structured array with `x` and `y` coordinates 
####     covering the [0,1]x[0,1] area (★★☆)

In [37]:
a = np.dtype([('x', 'f4'), ('y', 'f4')])
print(a)
a = np.linspace(0,1,10)
b = a[np.newaxis, :]


[('x', '<f4'), ('y', '<f4')]


In [46]:
Z = np.zeros((5,5), [('x',float),('y',float)])
# Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
#                              np.linspace(0,1,5))
Z['x']= np.arange(25).reshape(5,5)
print(Z)
print(Z[3,2]['x'])

[[( 0., 0.) ( 1., 0.) ( 2., 0.) ( 3., 0.) ( 4., 0.)]
 [( 5., 0.) ( 6., 0.) ( 7., 0.) ( 8., 0.) ( 9., 0.)]
 [(10., 0.) (11., 0.) (12., 0.) (13., 0.) (14., 0.)]
 [(15., 0.) (16., 0.) (17., 0.) (18., 0.) (19., 0.)]
 [(20., 0.) (21., 0.) (22., 0.) (23., 0.) (24., 0.)]]
17.0


In [ ]:
#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [ ]:
#### 48. Print the minimum and maximum representable value 
####       for each numpy scalar type (★★☆)

In [49]:
dtypes_i = [np.int8, np.int16, np.int32, np.int64, np.uint8, np.uint16, np.uint32, np.uint64, np.intp, np.uintp]
dtypes_f = [np.float32, np.float64]
dtypes_c = [np.complex64, np.complex128]

for x in dtypes_i:
    print(np.iinfo(x))

for x in dtypes_f:
    print(np.finfo(x))

for x in dtypes_c:
    print(np.finfo(x))



Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------

Machine parameters for uint16
-----------------------------

In [ ]:
#### 49. How to print all the values of an array? (★★☆)

In [52]:
a = (i**2 for i in range(10))
print(list(a))

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]


In [ ]:
#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [53]:
a = np.random.random(10) * 10
b = 5
c = np.abs(a-b).argmin()
print(a)
print(b)
print(c)
print(a[c])


[9.48849998 7.89811069 6.35058909 9.11635544 3.33055681 1.26884298
 7.37344868 7.08103113 8.53047622 9.1872408 ]
5
2
6.350589094616303


In [ ]:
#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) 

In [54]:
color_coord = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte),
                  ('x', np.float32),
                  ('y', np.float32),
                 ])
a = np.ones((5,2), dtype=color_coord)
print(a)

[[(1, 1, 1, 1, 1., 1.) (1, 1, 1, 1, 1., 1.)]
 [(1, 1, 1, 1, 1., 1.) (1, 1, 1, 1, 1., 1.)]
 [(1, 1, 1, 1, 1., 1.) (1, 1, 1, 1, 1., 1.)]
 [(1, 1, 1, 1, 1., 1.) (1, 1, 1, 1, 1., 1.)]
 [(1, 1, 1, 1, 1., 1.) (1, 1, 1, 1, 1., 1.)]]


In [74]:
color_coord = [('position', [ ('x', float, 1),
                              ('y', float, 1)]),
               ('color',    [ ('r', float, 1),
                              ('g', float, 1),
                              ('b', float, 1)])]
a = np.ones((5), dtype=color_coord)
print(a, '\n')
a[1:3]['position']['x'] = 4
print(a)


[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.))] 

[((1., 1.), (1., 1., 1.)) ((4., 1.), (1., 1., 1.))
 ((4., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.))]


In [82]:
#### 52. Consider a random vector with shape (100,2) 
#        representing coordinates, find point by point distances (★★☆)
a = np.random.randint(0, 100, (10, 2))
b = np.diff(a, axis=0)
c = b ** 2
d = np.sum(c, axis=1)
e = d ** 0.5
print('shape(a) = ', a.shape, '\n', a)
print('shape(b) = ', b.shape, '\n', b)
print('shape(c) = ', c.shape, '\n', c)
print('shape(d) = ', d.shape, '\n', d)
print('shape(e) = ', e.shape, '\n', e)




shape(a) =  (10, 2) 
 [[83 46]
 [53 44]
 [ 3 66]
 [42 98]
 [59 46]
 [18 22]
 [77 26]
 [44 79]
 [90 42]
 [66 56]]
shape(b) =  (9, 2) 
 [[-30  -2]
 [-50  22]
 [ 39  32]
 [ 17 -52]
 [-41 -24]
 [ 59   4]
 [-33  53]
 [ 46 -37]
 [-24  14]]
shape(c) =  (9, 2) 
 [[ 900    4]
 [2500  484]
 [1521 1024]
 [ 289 2704]
 [1681  576]
 [3481   16]
 [1089 2809]
 [2116 1369]
 [ 576  196]]
shape(d) =  (9,) 
 [ 904 2984 2545 2993 2257 3497 3898 3485  772]
shape(e) =  (9,) 
 [30.06659276 54.62600113 50.44799302 54.70831747 47.50789408 59.13543777
 62.43396512 59.03388857 27.78488798]


In [ ]:
#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [84]:
a = np.ones(10, dtype=np.float32)
repr(a)
a.dtype = np.int32
repr(a)


'array([1065353216, 1065353216, 1065353216, 1065353216, 1065353216,\n       1065353216, 1065353216, 1065353216, 1065353216, 1065353216])'

In [ ]:
#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [ ]:
#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [ ]:
#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [87]:
a = np.arange(12)
b = np.random.choice(a, a.size)
c = b.reshape(3,4)
print(a, '\n', b, '\n', c)

[ 0  1  2  3  4  5  6  7  8  9 10 11] 
 [ 6  4  9  6 11 11  5  8  3  1 10 11] 
 [[ 6  4  9  6]
 [11 11  5  8]
 [ 3  1 10 11]]


In [ ]:
#### 58. Subtract the mean of each row of a matrix (★★☆)

In [90]:
a = np.arange(12).reshape(3,4)
b = np.mean(a, axis=1)
c = b[:, np.newaxis]
d = a-c
print(a, '\n', b, '\n', c, '\n', d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 [1.5 5.5 9.5] 
 [[1.5]
 [5.5]
 [9.5]] 
 [[-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]
 [-1.5 -0.5  0.5  1.5]]


In [ ]:
#### 59. How to sort an array by the nth column? (★★☆)

In [95]:
a = np.random.randint(0,10,(9,3))
b = a[:,1].argsort()
c = a[b]
print(a, '\n', b, '\n', c, )

[[2 8 7]
 [3 4 2]
 [5 9 1]
 [5 6 4]
 [9 2 6]
 [0 0 8]
 [8 1 3]
 [4 5 4]
 [9 4 3]] 
 [5 6 4 1 8 7 3 0 2] 
 [[0 0 8]
 [8 1 3]
 [9 2 6]
 [3 4 2]
 [9 4 3]
 [4 5 4]
 [5 6 4]
 [2 8 7]
 [5 9 1]]


In [ ]:
#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [ ]:
#### 61. Find the nearest value from a given value in an array (★★☆)

In [106]:
a = np.random.random(30).reshape((5,6)) * 10
b = np.abs(a - 5)
c = np.argmin(b.flat)
d = b.flat[c]
e = np.unravel_index(c, a.shape)
print(a, '\n'*2, b,'\n'*2, c, '\n', d, '\n', e)

[[9.76497086 0.90812444 7.2067668  0.78010559 9.04856129 4.60444002]
 [6.75384057 2.08161072 9.1807665  1.43614092 1.11803923 3.44931443]
 [5.23343062 4.35058804 4.35183    1.42627178 1.6063931  2.51461452]
 [5.12620964 9.1489929  2.80146207 3.25482594 4.0414015  3.19191671]
 [1.10330422 6.21630351 7.77451383 2.31820443 1.91931184 1.10862337]] 

 [[4.76497086 4.09187556 2.2067668  4.21989441 4.04856129 0.39555998]
 [1.75384057 2.91838928 4.1807665  3.56385908 3.88196077 1.55068557]
 [0.23343062 0.64941196 0.64817    3.57372822 3.3936069  2.48538548]
 [0.12620964 4.1489929  2.19853793 1.74517406 0.9585985  1.80808329]
 [3.89669578 1.21630351 2.77451383 2.68179557 3.08068816 3.89137663]] 

 18 
 0.12620964066752283 
 (3, 0)


In [ ]:
#### 62. Considering two arrays with shape (1,3) and (3,1), 
###      how to compute their sum using an iterator? (★★☆)

In [108]:
a = np.arange(3).reshape(1,3)
b = np.arange(3).reshape(3,1)

mysum = 0
for i in np.nditer(a):
    mysum += i
        
print(a, '\n'*2, b,'\n'*2, mysum)

[[0 1 2]] 

 [[0]
 [1]
 [2]] 

 3


In [113]:
a = np.arange(15)
b = np.arange(15).reshape(3,5)

a[...] = 5
print(a)

[5 5 5 5 5 5 5 5 5 5 5 5 5 5 5]


In [112]:
b[...]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [ ]:
#### 63. Create an array class that has a name attribute (★★☆)

In [ ]:
#### 64. Consider a given vector, 
# how to add 1 to each element indexed by a second vector 
# (be careful with repeated indices)? (★★★)

In [ ]:
#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [ ]:
#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [ ]:
#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [ ]:
#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
#### 69. How to get the diagonal of a dot product? (★★★)

In [ ]:
#### 70. Consider the vector [1, 2, 3, 4, 5], 
#  how to build a new vector with 
# 3 consecutive zeros interleaved between each value? (★★★)

In [ ]:
#### 71. Consider an array of dimension (5,5,3), 
# how to mulitply it by an array with dimensions (5,5)? (★★★)

In [ ]:
#### 72. How to swap two rows of an array? (★★★)

In [118]:
A = np.arange(25).reshape(5,5)
print(A)
print(A[[1,3]])

A[[0,1]] = A[[1,0]]
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [ ]:
#### 73. Consider a set of 10 triplets describing 10 triangles 
## (with shared vertices), 
## find the set of unique line segments composing all the  triangles (★★★)

In [ ]:
#### 74. Given an array C that is a bincount, 
###       how to produce an array A such that np.bincount(A) == C? (★★★)


In [ ]:
#### 75. How to compute averages using a sliding window over an array? (★★★)

In [ ]:
#### 76. Consider a one-dimensional array Z, 
#build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) 
#and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [ ]:
#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [127]:
a = np.array([0, 1, 2], dtype=bool)
b = np.array([0, 1, 2], dtype=np.float)
print(np.logical_not(a))
np.negative(b, b)
print(b)

[ True False False]
[-0. -1. -2.]


In [ ]:
#### 78. Consider 2 sets of points P0,P1 describing lines (2d) 
# and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [ ]:
#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [ ]:
#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:
#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], 
# how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [ ]:
#### 82. Compute a matrix rank (★★★)

In [ ]:
#### 83. How to find the most frequent value in an array?

In [ ]:
#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [ ]:
#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [ ]:
#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [ ]:
#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [ ]:
#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
#### 89. How to get the n largest values of an array (★★★)

In [129]:
a = np.random.randint(0, 100, (10))
print(a)
a.sort()
a[-4:]

[70 94 70 14 28 83 10 47 37 35]


array([70, 70, 83, 94])

In [ ]:
#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [ ]:
#### 91. How to create a record array from a regular array? (★★★)

In [ ]:
#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [ ]:
#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [ ]:
#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [ ]:
#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [ ]:
#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [ ]:
#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [ ]:
#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [ ]:
#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)