In [1]:
import numpy as np

In [2]:
from IPython.core.interactiveshell import InteractiveShell
# InteractiveShell.ast_node_interactivity I can only get last_expr_or_assign to work
InteractiveShell.ast_node_interactivity = "last_expr_or_assign"

In [9]:
a = list(range(0,10))

In [10]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [11]:
a[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [16]:
a[4::-1]

[4, 3, 2, 1, 0]

In [17]:
a[:3:-1]

[9, 8, 7, 6, 5, 4]

In [18]:
a[8:2:-1]

[8, 7, 6, 5, 4, 3]

In [20]:
a[8:2:-3]

[8, 5]

In [21]:
a[6::1]

[6, 7, 8, 9]

In [22]:
a[6::-1]

[6, 5, 4, 3, 2, 1, 0]

In [23]:
a[-3::1]

[7, 8, 9]

In [24]:
a[-3::-1]

[7, 6, 5, 4, 3, 2, 1, 0]

In [25]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [26]:
a[:-3:-1]

[9, 8]

In [27]:
a[7:2:-1]

[7, 6, 5, 4, 3]

In [28]:
a[-3:2:-1]

[7, 6, 5, 4, 3]

In [29]:
a[::-1]

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]

In [30]:
a[1::-1]

[1, 0]

In [31]:
a[:-3:-1]

[9, 8]

In [32]:
a[-3::-1]

[7, 6, 5, 4, 3, 2, 1, 0]

In [33]:
# seq[high::-stride]
a[5::-1]

[5, 4, 3, 2, 1, 0]

In [34]:
# seq[:low:-stride]
a[:5:-1]

[9, 8, 7, 6]

In [35]:
a[1::-1]

[1, 0]

In [36]:
a[:-3:-1]

[9, 8]

In [37]:
a[10:-3:-1]

[9, 8]

In [38]:
a[9:-3:-1]

[9, 8]

In [39]:
a[-3::-1]

[7, 6, 5, 4, 3, 2, 1, 0]

In [40]:
a[-3:0:-1]

[7, 6, 5, 4, 3, 2, 1]

In [41]:
a[:-3:-1]

[9, 8]

In [42]:
a[9:7:-1]

[9, 8]

In [43]:
# seq[high::-stride]
a[5::-1]

[5, 4, 3, 2, 1, 0]

In [44]:
# seq[:low:-stride]
a[:5:-1]

[9, 8, 7, 6]

In [45]:
a[-2:5:-1]

[8, 7, 6]

In [46]:
a[50:5:-1]

[9, 8, 7, 6]

In [56]:
a = [['A', 'B', 'C', 'D', 'E'],
       ['F', 'G', 'H', 'I', 'J'],
       ['K', 'L', 'M', 'N', 'O'],
       ['P', 'Q', 'R', 'S', 'T'],
       ['U', 'V', 'W', 'X', 'Y']]

[['A', 'B', 'C', 'D', 'E'],
 ['F', 'G', 'H', 'I', 'J'],
 ['K', 'L', 'M', 'N', 'O'],
 ['P', 'Q', 'R', 'S', 'T'],
 ['U', 'V', 'W', 'X', 'Y']]

In [57]:
a = np.array(a)

array([['A', 'B', 'C', 'D', 'E'],
       ['F', 'G', 'H', 'I', 'J'],
       ['K', 'L', 'M', 'N', 'O'],
       ['P', 'Q', 'R', 'S', 'T'],
       ['U', 'V', 'W', 'X', 'Y']], dtype='<U1')

In [58]:
a_indexed = a[[4,3,1], [2,4,0]]

array(['W', 'T', 'F'], dtype='<U1')

In [60]:
rows = np.array([0,2,1])
cols = np.array([2])
rows, cols

(array([0, 2, 1]), array([2]))

In [61]:
ix = np.broadcast(rows, cols)

In [62]:
print(ix.shape)

(3,)


In [63]:
print(*ix)

(0, 2) (2, 2) (1, 2)


In [64]:
a[rows, cols]

array(['C', 'M', 'H'], dtype='<U1')

In [1]:
patient = np.array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1])
emply3 = np.array([[0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
                   [0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0],
                   [0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]).transpose()

In [6]:
p_shape = patient.shape
e_shape = emply3.shape
print(f'{len(p_shape)=}\n{len(e_shape)=}')
print(f'{p_shape=}\n{e_shape=}')

len(p_shape)=1
len(e_shape)=2
p_shape=(19,)
e_shape=(19, 3)


In [4]:
patient_t = patient.transpose()

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

len(p_shape)=1
len(e_shape)=2


In [9]:
patient2 = patient[:, np.newaxis]
print(patient2.shape, patient2)

(19, 1) [[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]]


In [11]:
print(patient2, emply3)
emply3 * patient2

[[0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]] [[0 0 0]
 [0 0 0]
 [0 0 0]
 [1 0 0]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 0]
 [1 1 0]
 [1 1 0]
 [1 1 0]
 [1 0 0]
 [1 1 0]
 [1 1 0]
 [1 1 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [0, 0, 0],
       [0, 0, 0],
       [1, 1, 0],
       [1, 1, 0],
       [0, 0, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 1, 0],
       [1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [13]:
a = np.nonzero(patient2)

(array([ 4,  5,  6,  7, 10, 11, 13, 14, 15, 16, 17, 18], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))

In [14]:
patient2

array([[0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [1]])

In [15]:
np.nonzero(patient2)

(array([ 4,  5,  6,  7, 10, 11, 13, 14, 15, 16, 17, 18], dtype=int32),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32))

In [16]:
np.nonzero(emply3)

(array([ 3,  4,  4,  4,  5,  5,  5,  6,  6,  6,  7,  7,  7,  8,  8,  9,  9,
        10, 10, 11, 11, 12, 13, 13, 14, 14, 15, 15, 16, 17, 18],
       dtype=int32),
 array([0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 0, 1, 0, 1, 0, 1, 0,
        0, 1, 0, 1, 0, 1, 0, 0, 0], dtype=int32))

In [17]:
np.nonzero(patient)

(array([ 4,  5,  6,  7, 10, 11, 13, 14, 15, 16, 17, 18], dtype=int32),)

In [19]:
patient

array([0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [20]:
np.argwhere(patient==1)

array([[ 4],
       [ 5],
       [ 6],
       [ 7],
       [10],
       [11],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18]], dtype=int32)

In [21]:
np.where(patient==1)

(array([ 4,  5,  6,  7, 10, 11, 13, 14, 15, 16, 17, 18], dtype=int32),)

In [22]:
np.nonzero(patient==1)

(array([ 4,  5,  6,  7, 10, 11, 13, 14, 15, 16, 17, 18], dtype=int32),)

In [23]:
temp1 = np.array([10, 9, 8, 7, 6, 5, 4, 3, 2, 1])
temp2 = np.delete(temp1, 2)
print(temp1, temp2)

[10  9  8  7  6  5  4  3  2  1] [10  9  7  6  5  4  3  2  1]
