In [1]:
# Notes on Numpy
# Created 9/29/20
# Started at https://numpy.org/doc/stable/

In [15]:
import numpy as np
rg = np.random.default_rng(1)

In [8]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
b = a.reshape(6,2)
print("a ", id(a), "\n", a)
print("b ", id(b), "\n", b)

a  94783272 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b  240338888 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


In [13]:
a.resize(4,3)
print("a ", id(a), "\n", a)

a  94783272 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [18]:
a = np.floor(10*rg.random((2,2)))
b = np.floor(10*rg.random((2,2)))
c = np.vstack((a,b))
print("a ", id(a), "\n", a)
print("b ", id(b), "\n", b)
print("c ", id(c), "\n", c)

a  240377752 
 [[1. 4.]
 [2. 2.]]
b  240386120 
 [[7. 2.]
 [4. 9.]]
c  240386160 
 [[1. 4.]
 [2. 2.]
 [7. 2.]
 [4. 9.]]


In [19]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))

In [24]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = a[:, np.newaxis]
c = a[np.newaxis, :]
d = b+c
print("a ", id(a), "\n", a)
print("b ", id(b), "\n", b)
print("c ", id(c), "\n", c)
print("d ", id(d), "\n", d)

a  240310736 
 [ 0. 10. 20. 30.]
b  240310616 
 [[ 0.]
 [10.]
 [20.]
 [30.]]
c  240377632 
 [[ 0. 10. 20. 30.]]
d  240386240 
 [[ 0. 10. 20. 30.]
 [10. 20. 30. 40.]
 [20. 30. 40. 50.]
 [30. 40. 50. 60.]]


In [32]:
a = np.arange(100).reshape(10, 10)
print(a.shape)
print(a)

(10, 10)
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [33]:
b = a[:, 3]
print(b)

[ 3 13 23 33 43 53 63 73 83 93]


In [35]:
c = a[::3, 4]
print(c)

[ 4 34 64 94]


In [54]:
a = np.ones((3, 4))
b = np.zeros(3)
c = b[:, np.newaxis]  # Slicing an array returns a view of it:
print('{}: shape={}, id={}\n{}\n'.format('a', a.shape, id(a), a))
print('{}: shape={}, id={}\n{}\n'.format('b', b.shape, id(b), b))
print('{}: shape={}, id={}\n{}\n'.format('c', c.shape, id(c), c))
c[2] = 4
print('{}: shape={}, id={}\n{}\n'.format('b', b.shape, id(b), b))
print('{}: shape={}, id={}\n{}\n'.format('c', c.shape, id(c), c))

a: shape=(3, 4), id=240401448
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

b: shape=(3,), id=240418472
[0. 0. 0.]

c: shape=(3, 1), id=240402048
[[0.]
 [0.]
 [0.]]

b: shape=(3,), id=240418472
[0. 0. 4.]

c: shape=(3, 1), id=240402048
[[0.]
 [0.]
 [4.]]



In [58]:
a = np.arange(12).reshape(3,4)
b = np.arange(3)
c = b[..., np.newaxis]  # Slicing an array returns a view of it:
d = a + c
print('{}: shape={}, id={}\n{}\n'.format('a', a.shape, id(a), a))
print('{}: shape={}, id={}\n{}\n'.format('b', b.shape, id(b), b))
print('{}: shape={}, id={}\n{}\n'.format('c', c.shape, id(c), c))
print('{}: shape={}, id={}\n{}\n'.format('d', d.shape, id(d), d))


a: shape=(3, 4), id=240276528
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

b: shape=(3,), id=240928832
[0 1 2]

c: shape=(3, 1), id=240929752
[[0]
 [1]
 [2]]

d: shape=(3, 4), id=240893368
[[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]]

